# Generated by Django 2.1.5 on 2019-03-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EspacePerso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='countrie',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='newslater',
        ),
    ]
