# Generated by Django 2.1.5 on 2019-03-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('content', models.TextField(default="Ceci est le contenu de l'article")),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=1, default=5, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nom du Programme', max_length=100)),
                ('description', models.TextField(default="Ceci est la description d'un programme")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('download_file', models.FileField(null=True, upload_to='executables')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_number', models.IntegerField(default=0)),
                ('favorite_number', models.IntegerField(default=0)),
                ('avarage_rating', models.IntegerField(default=5)),
                ('program_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.Program')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='program_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.Program'),
        ),
        migrations.AddField(
            model_name='article',
            name='program_ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.Program'),
        ),
    ]
