# Generated by Django 2.1.5 on 2019-07-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_auto_20190430_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='app_functionnality',
            field=models.IntegerField(default=5, verbose_name="fonctionalité de l'application"),
        ),
        migrations.AlterField(
            model_name='stat',
            name='ease_of_setting_up_the_app',
            field=models.IntegerField(default=5, verbose_name="facilité de paramétrage de l'application"),
        ),
        migrations.AlterField(
            model_name='stat',
            name='other_comment_on_the_app',
            field=models.TextField(null=True, verbose_name="autre commentaire sur l'application"),
        ),
        migrations.AlterField(
            model_name='stat',
            name='other_comment_on_the_site',
            field=models.TextField(null=True, verbose_name='autre commentaire sur le site'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='other_message',
            field=models.TextField(null=True, verbose_name='autre message'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='overall_app_note',
            field=models.IntegerField(default=5, verbose_name="note générale de l'application"),
        ),
        migrations.AlterField(
            model_name='stat',
            name='overall_site_note',
            field=models.IntegerField(default=5, verbose_name='note générale attibuée au site'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='program_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.Program'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='site_accessibility',
            field=models.IntegerField(default=5, verbose_name='accessibilité du site'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='site_usefulness',
            field=models.IntegerField(default=5, verbose_name="facilité d'utilisation du site"),
        ),
        migrations.AlterField(
            model_name='stat',
            name='understand_of_record',
            field=models.IntegerField(default=5, verbose_name='compréhension de la notice'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='utility_of_record',
            field=models.IntegerField(default=5, verbose_name='utilité de la notice'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='what_functionality_would_you_like_on_the_app',
            field=models.TextField(null=True, verbose_name="quelle fonctionalité voudriez-vous ajouter sur l'application  ?"),
        ),
        migrations.AlterField(
            model_name='stat',
            name='what_functionality_would_you_like_on_the_site',
            field=models.TextField(null=True, verbose_name='quelle fonctionalité voudriez-vous ajouter au site ?'),
        ),
    ]
