# Generated by Django 2.1.5 on 2019-07-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0004_auto_20190701_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSytem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Windows', models.BooleanField(default=True)),
                ('Linux', models.BooleanField(default=True)),
                ('MacOs', models.BooleanField(default=True)),
                ('Android', models.BooleanField(default=True)),
                ('IOS', models.BooleanField(default=True)),
                ('WindowsPhone', models.BooleanField(default=True)),
            ],
        ),
    ]
