# Generated by Django 2.1.5 on 2019-07-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0006_auto_20190701_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingsytem',
            old_name='MacO',
            new_name='MacOS',
        ),
    ]
