# Generated by Django 2.1.5 on 2019-07-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0010_operatingsytem_operating_system_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Windows10', models.BooleanField(default=True)),
                ('OldVersionsWindows', models.BooleanField(default=True)),
                ('Linux', models.BooleanField(default=True)),
                ('MacOS', models.BooleanField(default=True)),
                ('Android', models.BooleanField(default=True)),
                ('IOS', models.BooleanField(default=True)),
                ('WindowsPhone', models.BooleanField(default=True)),
                ('program_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.Program')),
            ],
        ),
        migrations.RemoveField(
            model_name='operatingsytem',
            name='operating_system_ref',
        ),
        migrations.RemoveField(
            model_name='operatingsytem',
            name='program_ref',
        ),
        migrations.DeleteModel(
            name='OperatingSytem',
        ),
        migrations.AddField(
            model_name='stat',
            name='operating_system_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.OperatingSystem'),
        ),
    ]
