# Generated by Django 2.1.5 on 2019-07-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EspacePerso', '0003_auto_20190320_1715'),
        ('bibliotheque', '0011_auto_20190702_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_site_note', models.IntegerField(default=5, verbose_name='note générale attibuée au site')),
                ('site_accessibility', models.IntegerField(default=5, verbose_name='accessibilité du site')),
                ('site_usefulness', models.IntegerField(default=5, verbose_name="facilité d'utilisation du site")),
                ('what_functionality_would_you_like_on_the_site', models.TextField(null=True, verbose_name='quelle fonctionalité voudriez-vous ajouter au site ?')),
                ('other_comment_on_the_site', models.TextField(null=True, verbose_name='autre commentaire sur le site')),
                ('overall_app_note', models.IntegerField(default=5, verbose_name="note générale de l'application")),
                ('ease_of_setting_up_the_app', models.IntegerField(default=5, verbose_name="facilité de paramétrage de l'application")),
                ('utility_of_record', models.IntegerField(default=5, verbose_name='utilité de la notice')),
                ('understand_of_record', models.IntegerField(default=5, verbose_name='compréhension de la notice')),
                ('app_functionnality', models.IntegerField(default=5, verbose_name="fonctionalité de l'application")),
                ('what_functionality_would_you_like_on_the_app', models.TextField(null=True, verbose_name="quelle fonctionalité voudriez-vous ajouter sur l'application  ?")),
                ('other_comment_on_the_app', models.TextField(null=True, verbose_name="autre commentaire sur l'application")),
                ('other_message', models.TextField(null=True, verbose_name='autre message')),
                ('program_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.Program')),
                ('user_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EspacePerso.Profil')),
            ],
        ),
        migrations.RemoveField(
            model_name='stat',
            name='app_functionnality',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='ease_of_setting_up_the_app',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='other_comment_on_the_app',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='other_comment_on_the_site',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='other_message',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='overall_app_note',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='overall_site_note',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='site_accessibility',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='site_usefulness',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='understand_of_record',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='user_ref',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='utility_of_record',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='what_functionality_would_you_like_on_the_app',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='what_functionality_would_you_like_on_the_site',
        ),
    ]
